cc_library(
  name = "common",
  srcs = glob(["*.cc"]),
  hdrs = glob(["*.h"]),
  deps = ["//des:des"],
  visibility = ["//transfer:__subpackages__",
                "//key_exchange:__subpackages__"],
)
