cc_library(
  name = "numerical",
  srcs = glob(["*.cc"]),
  hdrs = glob(["*.h"]),
  visibility = ["//makeup_exam:__subpackages__",
                "//key_exchange:__subpackages__",
                "//semantic_security:__subpackages__"],
)
