cc_test(
  name = "test_blum_goldwasser",
  srcs = ["test_blum_goldwasser.cc"],
  deps = ["//semantic_security",
          "@gtest//:gtest"],
  size = "small",
  copts = ["-Iexternal/gtest/googletest/include"],
)
